### ISSUE TITLE
[Feature Request] Remember window position on restart

### ISSUE THREAD

**Issue by cozykitten** [SpikeHD/Dorion#123]
**Is your feature request related to a problem? Please describe.**
When restarting Dorion the window returns to being a small square

**Describe the solution you'd like**
It would be great if it could remember it's window position and size on close, f.e. I usually snap it to the right side and when I restart vanilla discord it also reopens on the right half of my screen, attached to the side.
![image](https://github.com/SpikeHD/Dorion/assets/116394977/58ad3abb-9377-48cc-bf29-fcec9dc94a0b)

**Comment by SpikeHD** [comment]
I've updated the window state plugin I use in 7b69128bbc782394dbfd521df8fe3ad9e8cef222, and it seems to work consistently on my Macbook, so this'll be available in the next release. Feel free to reopen if it isn't fixed.

**Comment by kajoken** [comment]
I just stumbled upon this post since I have exactly the same problem. Just installed Dorion v4.1.1 and it doesn't remember window positions at all. Do I need to actively download the mentioned window state plugin or should this normally work now?

OS: Windows 11, I have a three monitor setup if that helps.

**Comment by SpikeHD** [comment]
@kajoken It should be working, the plugin I am referring to is a plugin integrated within the program, not anything user-facing. It may just be something wrong with the [plugin itself](https://github.com/tauri-apps/plugins-workspace). I've updated some of the git dependencies (including the window-state plugin), and you can try an [Actions build](https://github.com/SpikeHD/Dorion/actions/runs/7769738187) to see if that's helped.

**Comment by kajoken** [comment]
@SpikeHD Thanks for the answer. I just tried the action build and it's exactly the same. It doesn't remember the window position at all. Not even on the same monitor. It always defaults back to a small window on the left side of my main monitor. I tried with or without Discord installed and after several reboots.

OS is Windows 11 Pro 23H2 Build 22631.3085

**Comment by cozykitten** [comment]
interesting, I also noticed that a few weeks back the default position shifted from some small window to the weird place I had it the day before, now it's stuck there instead.
I mean I just readjust it every day when I launch dorion but ye.
mightve been a webview2 update then

**Comment by kajoken** [comment]
Today I tested some more with Version 4.1.2.

It looks like some of the problems have been fixed. The Window now remembers the monitor position but it still doesn't remember the window size. I moved the window around on my monitors and the window will always open in the exact size I set it up before reinstalling Webview2. Reinstalling Webview2 does nothing for me now. Not sure what's up. It's a minor issue for me though since I usually don't change the windows position again after first setup.
