### ISSUE TITLE
[Bug] Minimized auto-start doesn't work

### ISSUE THREAD

**Issue by i3sey** [SpikeHD/Dorion#155]
**Describe the bug**
App opens on start, but not minimized in tray

**To Reproduce**
1. turn on parameters on the screenshot
2. save config
3. restart pc

**Expected behavior**
minimized dorion

**Screenshots**
![Снимок экрана 2023-11-12 111224](https://github.com/SpikeHD/Dorion/assets/86531179/384f2075-f488-48c0-8955-50265fce7019)

**System Info (please complete the following information):**
 - OS: win 10 pro
 - Version: Dorion V2.2.1
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
Should be fixed in 94b43ae. If its bothering you, you can use install via [build actions](https://github.com/SpikeHD/Dorion/actions/runs/6839323731)

**Comment by i3sey** [comment]
It appears again...

**Comment by i3sey** [comment]
[config.json](https://github.com/user-attachments/files/17166784/config.json)
![Capture](https://github.com/user-attachments/assets/45ba7ec3-03af-477f-b94a-35863713c72c)
but dorion still opens maximized, not in tray

**Comment by SpikeHD** [comment]
Weird... I used your exact config and it worked fine. Are you on Win 10 still? And on Dorion v6.0.3? Have you reinstalled Dorion (as in, not just updated, but entirely removed and re-added) since the first time you created this issue?

**Comment by i3sey** [comment]
![image](https://github.com/user-attachments/assets/98aed1b9-6480-474d-81a9-ff5c3bdd7805)
I just reinstalled dorion, but it still doesn't work. In the registry, I noticed that there is no --silent option or something like that

**Comment by SpikeHD** [comment]
Ah! Good catch, I had forgotten that flag when I moved over to the `tauri_plugin_autostart` plugin. That's fixed in https://github.com/SpikeHD/Dorion/commit/c863733ea0c6efc064525745e7656144dadf6430 and will be available in the next release (or, if it bothers you, you can download an [Actions build](https://github.com/SpikeHD/Dorion/actions/runs/11080072187))
