### ISSUE TITLE
[Bug] Corrupt config file

### ISSUE THREAD

**Issue by Isemenuk27** [SpikeHD/Dorion#204]
Client closes without any errors the next moment it launches.

latest.log file:
```
Failed to parse config, using default config!
Error: EOF while parsing a value at line 2 column 0
Safemode enabled: false
Failed to parse config, using default config!
Error: EOF while parsing a value at line 2 column 0
Joining...
Plugins updated
Failed to parse config, using default config!
Error: EOF while parsing a value at line 2 column 0
```

 - Windows 7
 - v4.1.2
 - All Windows updates installed.

**Comment by SpikeHD** [comment]
Send the contents of %appdata%/dorion/config.json, deleting it should fix this but I’d like to see whats wrong with it too

**Comment by Isemenuk27** [comment]
I installed portable version, because trying to use installer results in error:
![New Bitmap Image](https://github.com/SpikeHD/Dorion/assets/77487254/8f32519f-f421-4bcb-b6f2-d99916e8fd6d)

I have no files in appdata/dorion.
I made try moving portable version it this folder, but it still fails.

**Comment by SpikeHD** [comment]
The config.json is in the same folder as your portable install, then

**Comment by Isemenuk27** [comment]
Its empty

**Comment by Isemenuk27** [comment]
No i doesn't, but i found old version where config is present

config.json file
```
{"theme":"none","zoom":"1.0","client_type":"default","sys_tray":false,"block_telemetry":false,"push_to_talk":false,"push_to_talk_keys":[],"cache_css":null,"use_native_titlebar":false,"start_maximized":false,"profile":null,"streamer_mode_detection":null,"rpc_server":null,"open_on_startup":null,"startup_minimized":null,"autoupdate":null,"update_notify":null,"desktop_notifications":null,"auto_clear_cache":null,"multi_instance":null,"disable_hardware_accel":null,"blur":null,"blur_css":null,"client_mods":["Shelter"],"unread_badge":null}
```

latest.log file:
```
Safemode enabled: false
Joining...
Plugins updated
```

Dorian again closes itself moment i start it.

**Comment by SpikeHD** [comment]
Try running Dorion via CMD (should just be something like `.\Dorion.exe`). It should spit out more logs than the logfile would have.

**Comment by Isemenuk27** [comment]
![New Bitmap Image](https://github.com/SpikeHD/Dorion/assets/77487254/2e7e43a2-c977-46f8-b0c2-7f9563bf4e9b)

It returns nothing

**Comment by SpikeHD** [comment]
Is Dorion already open? If so, close it. Is it prompting for admin? If so, run CMD as admin first

**Comment by Isemenuk27** [comment]
![New Bitmap Image](https://github.com/SpikeHD/Dorion/assets/77487254/31fce190-bc55-4632-abb6-a03b5973faac)

It appears for a moment in task manager and closes
![New Bitmap Image](https://github.com/SpikeHD/Dorion/assets/77487254/2e994a6c-7761-460d-8f02-cc1d2a5c5527)

**Comment by SpikeHD** [comment]
Did Dorion ever open properly to begin with? Going off of this old issue, installing WV2 manually seemed to work for them: https://github.com/SpikeHD/Dorion/issues/9

**Comment by SpikeHD** [comment]
That should be made into a new issue
